apiVersion: v1
kind: Secret
metadata:
  name: stash-license
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "stash.labels" . | nindent 4 }}
type: Opaque
data:
  license-key: {{ .Values.product.licenseKey | b64enc }}
